image: alpine/edge
packages:
  - git
  - openssh
  - openssl
  - rsync
sources:
  - https://git.sr.ht/~sumner/infrastructure
secrets:
  # SSH Known Hosts
  - a9b7dc2e-293f-4fea-aec7-618689d4e5f2
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
  # Secrets Password File
  - 2414c42a-6bbf-4f1f-a82e-cd64d661c31c
environment:
  SECRETS_FILE_PATH: /home/build/.secrets_password_file
tasks:
  # Send all of the secrets to the server.
  - send-secrets: |
      cd infrastructure
      ./secrets_file_manager.sh extract
      rsync -vr --delete-after secrets/ root@deploy.sumnerevans.com:/etc/nixos/secrets
      rm -rf $SECRETS_FILE_PATH secrets

  # SSH into the server and switch to this commit
  - switch-commit: |
      cd infrastructure
      ssh root@deploy.sumnerevans.com "cd /etc/nixos && git fetch && git reset --hard $(git rev-parse HEAD)"

  # Running nixos-rebuild build
  - nix-build: |
      ssh root@deploy.sumnerevans.com "nixos-rebuild build --show-trace"

  # Switch to the new generation
  - switch-generation: |
      ssh root@deploy.sumnerevans.com "nixos-rebuild switch"
