image: nixos/unstable
packages:
  - nixos.bash
  - nixos.git
  - nixos.openssh
  - nixos.openssl
  - nixos.rst2html5
  - nixos.rsync
sources:
  - https://git.sr.ht/~sumner/infrastructure
secrets:
  # README Personal Access Token
  - 2fb5fd72-fa96-46c6-ab90-6b7cabebba16
  # SSH Known Hosts
  - 5f8876fe-b2b7-44f8-8ad5-6fa9bffbc52a
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
  # Secrets Password File
  - 2414c42a-6bbf-4f1f-a82e-cd64d661c31c
environment:
  SECRETS_FILE_PATH: /home/build/.secrets_password_file
  REPO_NAME: infrastructure
triggers:
  - action: email
    condition: failure
    to: alerts@sumnerevans.com
tasks:
  # Skip everything if not on master.
  - skip_not_master: |
      cd $REPO_NAME
      git branch --contains | grep master || echo "Skipping README deploy since not on master"
      git branch --contains | grep master || complete-build

  - setup: |
      echo "cd $REPO_NAME" >> ~/.buildenv

  - set_readme: |
      set +x
      set -e
      rst2html5 README.rst | \
        curl -H "Content-Type: text/html" \
             -H "Authorization: Bearer $(cat ~/.readme-token)" \
             -XPUT \
             --data-binary @- \
             "https://git.sr.ht/api/repos/${REPO_NAME}/readme"

  - send-secrets: |
      ./secrets_file_manager.sh extract
      rsync -vr --delete-after secrets/ root@bespin.sumnerevans.com:/etc/nixos/secrets
      rm -rf $SECRETS_FILE_PATH secrets

  - switch-commit: |
      ssh root@bespin.sumnerevans.com "cd /etc/nixos && git fetch && git reset --hard $(git rev-parse HEAD)"

  - remote-build: |
      ssh root@bespin.sumnerevans.com "nixos-rebuild build --show-trace"

  - switch-generation: |
      ssh root@bespin.sumnerevans.com "nixos-rebuild switch --show-trace"
