image: nixos/unstable
packages:
  - nixos.bash
  - nixos.git
  - nixos.openssh
  - nixos.openssl
  - nixos.rst2html5
  - nixos.rsync
sources:
  - https://git.sr.ht/~sumner/infrastructure
secrets:
  # README Personal Access Token
  - 2fb5fd72-fa96-46c6-ab90-6b7cabebba16
  # SSH Known Hosts
  - 5f8876fe-b2b7-44f8-8ad5-6fa9bffbc52a
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
  # Secrets Password File
  - 2414c42a-6bbf-4f1f-a82e-cd64d661c31c
environment:
  SECRETS_FILE_PATH: /home/build/.secrets_password_file
  REPO_NAME: infrastructure
triggers:
  - action: email
    condition: failure
    to: alerts@sumnerevans.com
tasks:
  - setup: |
      echo "cd $REPO_NAME" >> ~/.buildenv

  # If we are on the master branch, compile the README.rst to HTML and set it
  # as the README for the repo.
  - readme: |
      set +x
      ./bin/deploy_readme

  # Send all of the secrets to the server.
  - send-secrets: |
      ./bin/send_secrets

  # Switch commits, build, and switch to the new generation
  - switch-generation: |
      ./bin/switch_generation
