image: archlinux
packages:
  - git
  - openssh
  - openssl
  - python-poetry
  - rsync
sources:
  - https://git.sr.ht/~sumner/infrastructure
secrets:
  # README Personal Access Token
  - 2fb5fd72-fa96-46c6-ab90-6b7cabebba16
  # SSH Known Hosts
  - a9b7dc2e-293f-4fea-aec7-618689d4e5f2
  # SSH Deploy Key
  - f219888a-80af-4275-a777-89e8c7d277f0
  # Secrets Password File
  - 2414c42a-6bbf-4f1f-a82e-cd64d661c31c
environment:
  SECRETS_FILE_PATH: /home/build/.secrets_password_file
  REPO_NAME: infrastructure
triggers:
  - action: email
    condition: failure
    to: ~sumner/public-inbox@lists.sr.ht
tasks:
  - setup: |
      cd ${REPO_NAME}
      poetry install --no-dev
      echo "cd $REPO_NAME" >> ~/.buildenv

  # If we are on the master branch, compile the README.rst to HTML and set it
  # as the README for the repo.
  - readme: |
      set +x
      git branch --contains | grep master &&
        poetry run rst2html5 README.rst |                           \
          curl -H "Content-Type: text/html"                         \
            -H "Authorization: Bearer $(cat ~/.readme-token)"       \
            -XPUT                                                   \
            --data-binary @-                                        \
            "https://git.sr.ht/api/repos/${REPO_NAME}/readme" &&
        echo "README set"

  # Send all of the secrets to the server.
  - send-secrets: |
      ./secrets_file_manager.sh extract
      rsync -vr --delete-after secrets/ root@deploy.sumnerevans.com:/etc/nixos/secrets
      rm -rf $SECRETS_FILE_PATH secrets

  # SSH into the server and switch to this commit
  - switch-commit: |
      ssh root@deploy.sumnerevans.com "cd /etc/nixos && git fetch && git reset --hard $(git rev-parse HEAD)"

  # Running nixos-rebuild build
  - nix-build: |
      ssh root@deploy.sumnerevans.com "nixos-rebuild build --show-trace"

  # Switch to the new generation
  - switch-generation: |
      ssh root@deploy.sumnerevans.com "nixos-rebuild switch"
